"""added notes ans history

Revision ID: 6497f34d2f4d
Revises: c7a98f89dab3
Create Date: 2026-01-31 15:06:59.980460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6497f34d2f4d'
down_revision = 'c7a98f89dab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('history', sa.String(length=10240), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('history')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
