"""empty message

Revision ID: c7a98f89dab3
Revises: 24ee07ca8fa7
Create Date: 2026-01-30 20:44:20.445116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a98f89dab3'
down_revision = '24ee07ca8fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=200), nullable=False, server_default='unspecified'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
